import os
from dotenv import find_dotenv, load_dotenv

load_dotenv()

NEO4J_URI=os.getenv('NEO4J_URI')
NEO4J_PASSWORD=os.getenv('NEO4J_PASSWORD')
NEO4J_USER=os.getenv('NEO4J_USER')

QDRANT_PATH=os.getenv('QDRANT_PATH')
QDRANT_COLLECTION=os.getenv('QDRANT_COLLECTION')

YANDEX_API_KEY=os.getenv('YANDEX_API_KEY')
CLOUD_API_KEY=os.getenv('CLOUD_API_KEY')
CLOUD_RU_URL=os.getenv('CLOUD_RU_URL')

INPUT_FOLDER=os.getenv('INPUT_FOLDER')
TEXT_OUTPUT_FOLDER=os.getenv('TEXT_OUTPUT_FOLDER')

VECTOR_SIZE=int(os.getenv('VECTOR_SIZE'))
SEMANTIC_BREAKPOINT_TYPE=os.getenv('SEMANTIC_BREAKPOINT_TYPE')
SEMANTIC_BREAKPOINT_THRESHOLD=float(os.getenv('SEMANTIC_BREAKPOINT_THRESHOLD'))

MAX_RETRIES=int(os.getenv('MAX_RETRIES'))
RETRY_DELAY=int(os.getenv('RETRY_DELAY'))
HYBRID_ALPHA=float(os.getenv('HYBRID_ALPHA'))

QDRANT_HOST = os.getenv("QDRANT_HOST", "qdrant")
QDRANT_PORT = int(os.getenv("QDRANT_PORT", 6333))


